#!/bin/bash
# from http://dv-zeuthen.desy.de/security/examples_for_usage_of_openssl_command/

echo "Certificate:"
openssl x509 -noout -text -in "$1"

echo "RSA private key:"
openssl rsa -noout -text -in "$1"
